# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc8-opt/bin/cmake

# The command to remove a file.
RM = /cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc8-opt/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data6/Users/mioh/DMG4/examples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data6/Users/mioh/DMG4/examples/GitBackup_DAMSA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc8-opt/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc8-opt/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc8-opt/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc8-opt/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc8-opt/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc8-opt/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc8-opt/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.20.0-790a8/x86_64-centos7-gcc8-opt/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data6/Users/mioh/DMG4/examples/GitBackup_DAMSA/CMakeFiles /data6/Users/mioh/DMG4/examples/GitBackup_DAMSA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data6/Users/mioh/DMG4/examples/GitBackup_DAMSA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mkgeant4

# Build rule for target.
mkgeant4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mkgeant4
.PHONY : mkgeant4

# fast build rule for target.
mkgeant4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/build
.PHONY : mkgeant4/fast

ActionInitialization.o: ActionInitialization.cc.o
.PHONY : ActionInitialization.o

# target to build an object file
ActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/ActionInitialization.cc.o
.PHONY : ActionInitialization.cc.o

ActionInitialization.i: ActionInitialization.cc.i
.PHONY : ActionInitialization.i

# target to preprocess a source file
ActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/ActionInitialization.cc.i
.PHONY : ActionInitialization.cc.i

ActionInitialization.s: ActionInitialization.cc.s
.PHONY : ActionInitialization.s

# target to generate assembly for a file
ActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/ActionInitialization.cc.s
.PHONY : ActionInitialization.cc.s

DarkMatterPhysicsConfigure.o: DarkMatterPhysicsConfigure.cc.o
.PHONY : DarkMatterPhysicsConfigure.o

# target to build an object file
DarkMatterPhysicsConfigure.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/DarkMatterPhysicsConfigure.cc.o
.PHONY : DarkMatterPhysicsConfigure.cc.o

DarkMatterPhysicsConfigure.i: DarkMatterPhysicsConfigure.cc.i
.PHONY : DarkMatterPhysicsConfigure.i

# target to preprocess a source file
DarkMatterPhysicsConfigure.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/DarkMatterPhysicsConfigure.cc.i
.PHONY : DarkMatterPhysicsConfigure.cc.i

DarkMatterPhysicsConfigure.s: DarkMatterPhysicsConfigure.cc.s
.PHONY : DarkMatterPhysicsConfigure.s

# target to generate assembly for a file
DarkMatterPhysicsConfigure.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/DarkMatterPhysicsConfigure.cc.s
.PHONY : DarkMatterPhysicsConfigure.cc.s

DetectorConstruction.o: DetectorConstruction.cc.o
.PHONY : DetectorConstruction.o

# target to build an object file
DetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/DetectorConstruction.cc.o
.PHONY : DetectorConstruction.cc.o

DetectorConstruction.i: DetectorConstruction.cc.i
.PHONY : DetectorConstruction.i

# target to preprocess a source file
DetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/DetectorConstruction.cc.i
.PHONY : DetectorConstruction.cc.i

DetectorConstruction.s: DetectorConstruction.cc.s
.PHONY : DetectorConstruction.s

# target to generate assembly for a file
DetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/DetectorConstruction.cc.s
.PHONY : DetectorConstruction.cc.s

EventAction.o: EventAction.cc.o
.PHONY : EventAction.o

# target to build an object file
EventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/EventAction.cc.o
.PHONY : EventAction.cc.o

EventAction.i: EventAction.cc.i
.PHONY : EventAction.i

# target to preprocess a source file
EventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/EventAction.cc.i
.PHONY : EventAction.cc.i

EventAction.s: EventAction.cc.s
.PHONY : EventAction.s

# target to generate assembly for a file
EventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/EventAction.cc.s
.PHONY : EventAction.cc.s

PMTHit.o: PMTHit.cc.o
.PHONY : PMTHit.o

# target to build an object file
PMTHit.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/PMTHit.cc.o
.PHONY : PMTHit.cc.o

PMTHit.i: PMTHit.cc.i
.PHONY : PMTHit.i

# target to preprocess a source file
PMTHit.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/PMTHit.cc.i
.PHONY : PMTHit.cc.i

PMTHit.s: PMTHit.cc.s
.PHONY : PMTHit.s

# target to generate assembly for a file
PMTHit.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/PMTHit.cc.s
.PHONY : PMTHit.cc.s

PMTSD.o: PMTSD.cc.o
.PHONY : PMTSD.o

# target to build an object file
PMTSD.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/PMTSD.cc.o
.PHONY : PMTSD.cc.o

PMTSD.i: PMTSD.cc.i
.PHONY : PMTSD.i

# target to preprocess a source file
PMTSD.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/PMTSD.cc.i
.PHONY : PMTSD.cc.i

PMTSD.s: PMTSD.cc.s
.PHONY : PMTSD.s

# target to generate assembly for a file
PMTSD.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/PMTSD.cc.s
.PHONY : PMTSD.cc.s

PrimaryGeneratorAction.o: PrimaryGeneratorAction.cc.o
.PHONY : PrimaryGeneratorAction.o

# target to build an object file
PrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/PrimaryGeneratorAction.cc.o
.PHONY : PrimaryGeneratorAction.cc.o

PrimaryGeneratorAction.i: PrimaryGeneratorAction.cc.i
.PHONY : PrimaryGeneratorAction.i

# target to preprocess a source file
PrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/PrimaryGeneratorAction.cc.i
.PHONY : PrimaryGeneratorAction.cc.i

PrimaryGeneratorAction.s: PrimaryGeneratorAction.cc.s
.PHONY : PrimaryGeneratorAction.s

# target to generate assembly for a file
PrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/PrimaryGeneratorAction.cc.s
.PHONY : PrimaryGeneratorAction.cc.s

Run.o: Run.cc.o
.PHONY : Run.o

# target to build an object file
Run.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/Run.cc.o
.PHONY : Run.cc.o

Run.i: Run.cc.i
.PHONY : Run.i

# target to preprocess a source file
Run.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/Run.cc.i
.PHONY : Run.cc.i

Run.s: Run.cc.s
.PHONY : Run.s

# target to generate assembly for a file
Run.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/Run.cc.s
.PHONY : Run.cc.s

RunAction.o: RunAction.cc.o
.PHONY : RunAction.o

# target to build an object file
RunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/RunAction.cc.o
.PHONY : RunAction.cc.o

RunAction.i: RunAction.cc.i
.PHONY : RunAction.i

# target to preprocess a source file
RunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/RunAction.cc.i
.PHONY : RunAction.cc.i

RunAction.s: RunAction.cc.s
.PHONY : RunAction.s

# target to generate assembly for a file
RunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/RunAction.cc.s
.PHONY : RunAction.cc.s

SteppingActionDMG4.o: SteppingActionDMG4.cc.o
.PHONY : SteppingActionDMG4.o

# target to build an object file
SteppingActionDMG4.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/SteppingActionDMG4.cc.o
.PHONY : SteppingActionDMG4.cc.o

SteppingActionDMG4.i: SteppingActionDMG4.cc.i
.PHONY : SteppingActionDMG4.i

# target to preprocess a source file
SteppingActionDMG4.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/SteppingActionDMG4.cc.i
.PHONY : SteppingActionDMG4.cc.i

SteppingActionDMG4.s: SteppingActionDMG4.cc.s
.PHONY : SteppingActionDMG4.s

# target to generate assembly for a file
SteppingActionDMG4.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/SteppingActionDMG4.cc.s
.PHONY : SteppingActionDMG4.cc.s

mkgeant4.o: mkgeant4.cc.o
.PHONY : mkgeant4.o

# target to build an object file
mkgeant4.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/mkgeant4.cc.o
.PHONY : mkgeant4.cc.o

mkgeant4.i: mkgeant4.cc.i
.PHONY : mkgeant4.i

# target to preprocess a source file
mkgeant4.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/mkgeant4.cc.i
.PHONY : mkgeant4.cc.i

mkgeant4.s: mkgeant4.cc.s
.PHONY : mkgeant4.s

# target to generate assembly for a file
mkgeant4.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkgeant4.dir/build.make CMakeFiles/mkgeant4.dir/mkgeant4.cc.s
.PHONY : mkgeant4.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... mkgeant4"
	@echo "... ActionInitialization.o"
	@echo "... ActionInitialization.i"
	@echo "... ActionInitialization.s"
	@echo "... DarkMatterPhysicsConfigure.o"
	@echo "... DarkMatterPhysicsConfigure.i"
	@echo "... DarkMatterPhysicsConfigure.s"
	@echo "... DetectorConstruction.o"
	@echo "... DetectorConstruction.i"
	@echo "... DetectorConstruction.s"
	@echo "... EventAction.o"
	@echo "... EventAction.i"
	@echo "... EventAction.s"
	@echo "... PMTHit.o"
	@echo "... PMTHit.i"
	@echo "... PMTHit.s"
	@echo "... PMTSD.o"
	@echo "... PMTSD.i"
	@echo "... PMTSD.s"
	@echo "... PrimaryGeneratorAction.o"
	@echo "... PrimaryGeneratorAction.i"
	@echo "... PrimaryGeneratorAction.s"
	@echo "... Run.o"
	@echo "... Run.i"
	@echo "... Run.s"
	@echo "... RunAction.o"
	@echo "... RunAction.i"
	@echo "... RunAction.s"
	@echo "... SteppingActionDMG4.o"
	@echo "... SteppingActionDMG4.i"
	@echo "... SteppingActionDMG4.s"
	@echo "... mkgeant4.o"
	@echo "... mkgeant4.i"
	@echo "... mkgeant4.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

